'use strict';

/**
 * Module dependencies. 
 */
var mongoose = require('mongoose'),    
    Course = mongoose.model('CourseDB'),
    config = require('meanio').loadConfig(),
    _ = require('lodash');





module.exports = function(Courses) {
    return {
        
        locate: function(req, res) {
            // use mongoose to get teh course
            Course.find(function(err, course) {

            // if there is an error retrieving, send the error. nothing after res.send(err) will execute
            if (err)
                res.send(err)

            res.json(course); // return the course in JSON format
        });
            

        },
       

        seed: function(req, res) {
           Course.create({  
            title : "Nodejs",
            version : 1.0,
            parts:[
            {
                id:1,
                part_id:1,
                title:'Part 1',
                facts:[
                {
                    name:'error1',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Reading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'error3',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Reading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Rereading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Rereading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Rereading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Rereading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Transition',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Transition',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Transition',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Transition',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Stop',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Stop',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Stop',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Stop',
                    type:'warning',
                    value:'value2'
                }
                ]
            },
            {
                id:2,
                part_id:2,
                title:'Part 2',
                facts:[
                {
                    name:'error1',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Reading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Reading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Reading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Rereading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Rereading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Rereading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Rereading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Transition',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Transition',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Transition',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Transition',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Stop',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Stop',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Stop',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Stop',
                    type:'warning',
                    value:'value2'
                }
                ]
            },
            {
                id:3,
                part_id:3,
                title:'Part 3',
                facts:[
                {
                    name:'error1',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Reading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Reading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Reading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Rereading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Rereading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Rereading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Rereading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Transition',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Transition',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Transition',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Transition',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Stop',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Stop',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Stop',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Stop',
                    type:'warning',
                    value:'value2'
                }
                ]
            },
            {
                id:4,
                part_id:4,
                title:'Part 4',
                facts:[
                {
                    name:'error1',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Reading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Reading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Reading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Rereading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Rereading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Rereading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Rereading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Transition',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Transition',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Transition',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Transition',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Stop',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Stop',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Stop',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Stop',
                    type:'warning',
                    value:'value2'
                }
                ]
            },
            {
                id:5,
                part_id:5,
                title:'Part 5',
                facts:[
                {
                    name:'error1',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Reading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Reading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Reading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Rereading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Rereading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Rereading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Rereading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Transition',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Transition',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Transition',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Transition',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Stop',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Stop',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Stop',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Stop',
                    type:'warning',
                    value:'value2'
                }
                ]
            },
            {
                id:6,
                part_id:6,
                title:'Part 6',
                facts:[
                {
                    name:'error1',
                    classof:'Reading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Reading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Reading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Reading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Rereading',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Rereading',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Rereading',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Rereading',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Transition',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Transition',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Transition',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Transition',
                    type:'warning',
                    value:'value2'
                },
                {
                    name:'error1',
                    classof:'Stop',
                    type:'issue',
                    value:'value1'
                },
                {
                    name:'error2',
                    classof:'Stop',
                    type:'issue',
                    value:'value2'
                },
                {
                    name:'warn1',
                    classof:'Stop',
                    type:'warning',
                    value:'value1'
                },
                {
                    name:'warn2',
                    classof:'Stop',
                    type:'warning',
                    value:'value2'
                }
                ]
            }


            ]

        }, function(err, todo) {
            if (err)
                res.send(err);

            res.send(todo);

        });

            

        }
    };
}